# Generated by Django 5.2.8 on 2026-01-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_author_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='review',
            name='review_author_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
