# Generated by Django 5.2.8 on 2026-01-17 10:36

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_subcategory_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='category', chained_model_field='parent', on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
