# Generated by Django 5.2.8 on 2026-01-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='freeDelivery',
            field=models.BooleanField(default=False),
        ),
    ]
