# Generated by Django 5.2.8 on 2026-01-27 13:08

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_freedelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='category', chained_model_field='parent', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
