# Generated by Django 5.2.8 on 2026-01-27 15:54

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='media/default_none.jpg', null=True, upload_to=products.models.product_images_directory_path),
        ),
    ]
