# Generated by Django 5.2.8 on 2026-01-16 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('basket', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('city', models.CharField(max_length=100, verbose_name='Delivery city')),
                ('delivery_address', models.TextField(max_length=200, verbose_name='Delivery address')),
                ('delivery_type', models.CharField(choices=[('delivery', 'Delivery'), ('express', 'Express delivery')], default='Delivery', max_length=20)),
                ('payment_type', models.CharField(choices=[('online', 'Online payment'), ('online_any', 'Online payment from a random account')], default='Online payment', max_length=20)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total order amount')),
                ('status', models.CharField(default='inProgress', max_length=255)),
                ('payment_error', models.CharField(blank=True, default='', max_length=255)),
                ('basket', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='basket.basket')),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profileuser', verbose_name='Buyer')),
                ('products', models.ManyToManyField(related_name='orders', to='products.product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
